name: cubetimer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  firebase_analytics: ^8.3.1
  fl_chart: ^0.36.3
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^9.1.0
  get: ^4.3.6
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  launch_review: ^3.0.1
  simple_animations: ^3.1.1
  statistics: ^1.0.4
  stop_watch_timer: ^1.3.1
  swipe: ^0.0.1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
      sdk: flutter  
  hive_generator: ^1.1.0
  lint: ^1.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/img/
